# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - "nightly"
    - 3.4
    - 3.3
    - 2.7
matrix:
    allow_failures:
        - python : "nightly"
install:
    - pip install pytest
script:
    - py.test
